import React, { useState } from "react";
import { Evidence, Help, Toggle } from "./ui";

type AdminSpace = "resources" | "offers" | "reminders";
type Props = { initialSpace?: AdminSpace; initialSection?: string; onHelp: (id: string) => void };

const days = ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"];

function AdminFrame({ space, onSpace, children }: { space: AdminSpace; onSpace: (space: AdminSpace) => void; children: React.ReactNode }) {
  return <div className="zs-product-frame zs-admin-frame"><aside className="zs-admin-rail"><div className="zs-rail-logo">Z</div>{["▦", "◎", "▤", "$", "↔", "♧", "⚙"].map((icon, index) => <button key={`${icon}-${index}`} className={index === 5 ? "active" : ""}>{icon}</button>)}</aside><main><header className="zs-product-top zs-admin-top"><button className="zs-menu-button" aria-label="Abrir menú">☰</button><div className="zs-wordmark"><span>Z</span><strong>ZellShip</strong></div><div className="zs-admin-context"><span>USD</span><b>$17.04 MXN</b><i>↔</i><span>1/1 almacén seleccionado</span><button>Cambiar</button></div><div className="zs-user"><span>RG</span><b>Admin⌄</b></div></header><div className="zs-admin-body"><div className="zs-admin-breadcrumb">Establecimientos <span>/</span> Faceup San Pedro</div><section className="zs-establishment-card"><div><h1>Faceup San Pedro</h1><span className="zs-live">Activo</span></div><dl><div><dt>Responsable</dt><dd>Admin Faceup</dd><small>admin@faceup.mx · 81 5555 0101</small></div><div><dt>Dirección</dt><dd>San Pedro Garza García, Nuevo León</dd><small>America/Monterrey</small></div></dl></section><section className="zs-admin-config"><h2>Configuraciones</h2><nav className="zs-admin-spaces">{([['resources','Recursos y disponibilidad'],['offers','Oferta y prestadores'],['reminders','Recordatorios']] as const).map(([id,label]) => <button className={space === id ? "active" : ""} onClick={() => onSpace(id)} key={id}>{label}</button>)}</nav>{children}</section></div></main></div>;
}

export function AdminView({ initialSpace = "resources", initialSection = "locations", onHelp }: Props) {
  const [space, setSpace] = useState<AdminSpace>(initialSpace);
  const [resource, setResource] = useState(initialSection);
  const [offerTab, setOfferTab] = useState(initialSection === "duration" ? "duration" : "eligibility");
  const [locations, setLocations] = useState([
    { name: "Cabina 01", enabled: true, capacity: 1, capability: 1, general: false },
    { name: "Cabina 02", enabled: true, capacity: 1, capability: 1, general: false },
    { name: "Cabina 03", enabled: false, capacity: 1, capability: 1, general: false },
    { name: "General", enabled: true, capacity: 50, capability: 25, general: true },
  ]);
  const [secondReminder, setSecondReminder] = useState(true);
  const [validated, setValidated] = useState(false);

  return <AdminFrame space={space} onSpace={(next) => { setSpace(next); if (next !== "resources") setResource("locations"); }}>
    {space === "resources" && <div><Subnav value={resource} onChange={setResource} items={[["locations","Service Locations"],["establishment","Establishment"],["providers","User / Worker"],["priority","Prioridad"],["blocks","Bloqueos"]]} />
      {resource === "locations" && <Locations locations={locations} setLocations={setLocations} onHelp={onHelp}/>}
      {resource === "establishment" && <EstablishmentAvailability />}
      {resource === "providers" && <ProviderAvailability onHelp={onHelp}/>}
      {resource === "priority" && <Priority onHelp={onHelp}/>}
      {resource === "blocks" && <Blocks />}
    </div>}
    {space === "offers" && <div><Subnav value={offerTab} onChange={setOfferTab} items={[["eligibility","Elegibilidad"],["duration","Duración, componentes y buffers"]]} />{offerTab === "eligibility" ? <Eligibility onHelp={onHelp}/> : <Duration onHelp={onHelp}/>}</div>}
    {space === "reminders" && <Reminders second={secondReminder} setSecond={setSecondReminder} validated={validated} setValidated={setValidated} onHelp={onHelp}/>}
  </AdminFrame>;
}

function Subnav({ value, onChange, items }: { value: string; onChange: (value: string) => void; items: string[][] }) {
  return <nav className="zs-subnav">{items.map(([id,label]) => <button key={id} className={value === id ? "active" : ""} onClick={() => onChange(id)}>{label}</button>)}</nav>;
}

function Locations({ locations, setLocations, onHelp }: { locations: {name:string;enabled:boolean;capacity:number;capability:number;general:boolean}[]; setLocations: React.Dispatch<React.SetStateAction<{name:string;enabled:boolean;capacity:number;capability:number;general:boolean}[]>>; onHelp:(id:string)=>void }) {
  return <div className="zs-admin-content"><header className="zs-section-head"><div><Evidence kind="to-be"/><h2>Service Locations para citas <Help id="location" onOpen={onHelp}/></h2><p>La configuración de Agenda no reemplaza la capacidad comercial actual.</p></div><button>＋ Agregar ubicación de servicio</button></header><label className="zs-table-search">Buscar <input aria-label="Buscar ubicación" placeholder="Buscar"/></label><div className="zs-table zs-locations-table"><div className="head"><b>Ubicación</b><b>Agenda</b><b>Capacidad de citas <Help id="capacity" onOpen={onHelp}/></b><b>Capability As-Is</b><b>Service Type</b><b>Acciones</b></div>{locations.map((location,index) => <div key={location.name}><span><strong>{location.name}</strong>{location.general && <small>Ubicación de sistema · no aparece como cabina</small>}</span><Toggle checked={location.enabled} label={location.enabled ? "Habilitada" : "Deshabilitada"} onChange={(enabled) => setLocations(current => current.map((item,i) => i === index ? {...item,enabled} : item))}/><label><input aria-label={`Capacidad de citas ${location.name}`} type="number" min="1" value={location.capacity} onChange={(event) => setLocations(current => current.map((item,i) => i === index ? {...item,capacity:Number(event.target.value)} : item))}/><small>citas simultáneas</small></label><span><strong>{location.capability}</strong><small>capacidad comercial</small></span><span><b>Consumo</b><small>As-Is</small></span><button className="zs-dots" aria-label={`Acciones de ${location.name}`}>⋮</button></div>)}</div><div className="zs-inline-info"><Evidence kind="as-is"/><p><b>Consumo</b> conserva <code>SERVICE_TYPE.InPlace = 'consumo'</code>. Product y Mix no se relacionan directamente con estas ubicaciones.</p></div></div>;
}

function EstablishmentAvailability() {
  const [enabled, setEnabled] = useState(days.map(() => true));
  return <div className="zs-admin-content"><header className="zs-section-head"><div><Evidence kind="to-be"/><h2>Disponibilidad del Establishment</h2><p>Los intervalos ofrecidos deben caber completos dentro del horario.</p></div><button className="zs-primary">Guardar cambios</button></header><div className="zs-split"><section className="zs-card"><h3>Horario semanal</h3>{days.map((day,index) => <div className="zs-schedule-row" key={day}><Toggle checked={enabled[index]} label={day} onChange={(next) => setEnabled(current => current.map((value,i) => i === index ? next : value))}/><input value="09:00" readOnly/><span>—</span><input value={day === "Sábado" ? "15:00" : "19:00"} readOnly/></div>)}</section><section className="zs-card"><h3>Contexto de Agenda</h3><label>Zona horaria<select defaultValue="America/Monterrey"><option>America/Monterrey</option></select></label><div className="zs-preview"><b>Próximo intervalo válido</b><strong>09:00–10:20</strong><span>Incluye 10 min antes y 10 min después</span></div><Evidence kind="pending">Persistencia y zona horaria</Evidence></section></div></div>;
}

function ProviderAvailability({ onHelp }: { onHelp:(id:string)=>void }) {
  const [selected, setSelected] = useState("Valeria González");
  return <div className="zs-admin-content"><header className="zs-section-head"><div><Evidence kind="to-be"/><h2>Disponibilidad de prestadores <Help id="provider" onOpen={onHelp}/></h2><p>User y Worker comparten la experiencia, no la entidad técnica.</p></div></header><div className="zs-split"><section className="zs-card"><h3>Prestador</h3>{["Valeria González · User","Ricardo Acosta · Worker","Daniela Salas · User","Mónica Herrera · Worker"].map(item => <button className={`zs-provider-choice ${selected === item.split(" · ")[0] ? "active" : ""}`} onClick={() => setSelected(item.split(" · ")[0])} key={item}>{item}</button>)}</section><section className="zs-card"><h3>{selected}</h3><p className="zs-muted">Hereda horario del Establishment con ajustes propios.</p>{days.slice(0,5).map(day => <div className="zs-schedule-row compact" key={day}><span>●</span><b>{day}</b><input value="09:00" readOnly/><span>—</span><input value="18:00" readOnly/></div>)}<div className="zs-inline-warning"><Help id="identity" onOpen={onHelp}/><span>La identidad compartida User/Worker sigue pendiente técnico.</span></div></section></div></div>;
}

function Priority({ onHelp }: { onHelp:(id:string)=>void }) {
  const [people,setPeople] = useState(["Valeria González · User","Ricardo Acosta · Worker","Daniela Salas · User","Mónica Herrera · Worker"]);
  const move = (index:number,delta:number) => setPeople(current => { const next=[...current]; const target=index+delta; if(target<0||target>=next.length)return current; [next[index],next[target]]=[next[target],next[index]]; return next; });
  return <div className="zs-admin-content"><header className="zs-section-head"><div><Evidence kind="to-be"/><h2>Prioridad de primer prestador disponible <Help id="provider" onOpen={onHelp}/></h2><p>La prioridad desempata únicamente entre prestadores elegibles y disponibles.</p></div></header><section className="zs-card zs-priority-list">{people.map((person,index)=><div key={person}><strong>{index+1}</strong><span><b>{person.split(" · ")[0]}</b><small>{person.split(" · ")[1]}</small></span><button disabled={index===0} onClick={()=>move(index,-1)}>↑</button><button disabled={index===people.length-1} onClick={()=>move(index,1)}>↓</button></div>)}</section><div className="zs-inline-info"><Evidence kind="pending"/><p>TI define persistencia, desempate e identidad canónica.</p></div></div>;
}

function Blocks() {
  const [showForm,setShowForm]=useState(false); const [saved,setSaved]=useState(false);
  return <div className="zs-admin-content"><header className="zs-section-head"><div><Evidence kind="to-be"/><h2>Bloqueos no recurrentes</h2><p>Excepciones por fecha y horario para un recurso específico.</p></div><button className="zs-primary" onClick={()=>setShowForm(true)}>＋ Nuevo bloqueo</button></header>{saved&&<div className="zs-success">✓ Bloqueo guardado · Ricardo Acosta · 29 ago · 13:00–14:00</div>}<div className="zs-table zs-block-table"><div className="head"><b>Recurso</b><b>Tipo</b><b>Fecha</b><b>Horario</b><b>Motivo</b></div><div><span>Valeria González</span><span>User</span><span>28 ago 2026</span><span>13:00–15:00</span><span>Capacitación</span></div><div><span>Cabina 02</span><span>Service Location</span><span>30 ago 2026</span><span>09:00–11:00</span><span>Mantenimiento</span></div></div>{showForm&&<section className="zs-inline-form"><header><h3>Nuevo bloqueo</h3><button className="zs-icon" onClick={()=>setShowForm(false)}>×</button></header><div className="zs-form-grid"><label>Tipo<select><option>User</option><option>Worker</option><option>Establishment</option><option>Service Location</option></select></label><label>Recurso<select><option>Ricardo Acosta</option><option>Valeria González</option><option>Cabina 01</option></select></label><label>Fecha<input type="date" defaultValue="2026-08-29"/></label><label>Desde<input type="time" defaultValue="13:00"/></label><label>Hasta<input type="time" defaultValue="14:00"/></label><label>Motivo<input defaultValue="Capacitación interna"/></label></div><footer><Evidence kind="pending">Persistencia por definir</Evidence><button className="zs-primary" onClick={()=>{setSaved(true);setShowForm(false)}}>Guardar bloqueo</button></footer></section>}</div>;
}

function Eligibility({ onHelp }: { onHelp:(id:string)=>void }) {
  const [selected,setSelected]=useState(["Valeria González","Ricardo Acosta"]);
  const people=["Valeria González · User","Ricardo Acosta · Worker","Daniela Salas · User","Mónica Herrera · Worker"];
  return <div className="zs-admin-content"><header className="zs-section-head"><div><Evidence kind="to-be"/><h2>Elegibilidad de oferta y prestador <Help id="offer" onOpen={onHelp}/></h2><p>Asignación explícita por Establishment. No relaciona oferta con Service Location.</p></div><button className="zs-primary">Guardar elegibilidad</button></header><div className="zs-split"><section className="zs-card"><label>Oferta<select><option>Hydrafacial Premium · Kit</option><option>Valoración facial · Servicio</option></select></label><div className="zs-offer-summary"><b>Hydrafacial Premium</b><span>Kit · 60 min base · Faceup San Pedro</span></div></section><section className="zs-card"><h3>Prestadores elegibles</h3>{people.map(item=>{const name=item.split(" · ")[0];return <label className="zs-check-row" key={item}><input type="checkbox" checked={selected.includes(name)} onChange={()=>setSelected(current=>current.includes(name)?current.filter(x=>x!==name):[...current,name])}/><span><b>{name}</b><small>{item.split(" · ")[1]}</small></span></label>})}</section></div></div>;
}

function Duration({ onHelp }: { onHelp:(id:string)=>void }) {
  const [led,setLed]=useState(true); const [before,setBefore]=useState(10); const [after,setAfter]=useState(10);
  const total=60+(led?20:0)+before+after;
  return <div className="zs-admin-content"><header className="zs-section-head"><div><Evidence kind="to-be"/><h2>Duración, componentes y buffers <Help id="duration" onOpen={onHelp}/></h2><p>Product y Mix conservan su catálogo comercial. La configuración sólo agrega reglas de Agenda.</p></div><button className="zs-primary">Guardar configuración</button></header><div className="zs-split"><section className="zs-card"><div className="zs-kind-tabs"><button>Servicio</button><button className="active">Kit</button></div><label>Oferta<select><option>Hydrafacial Premium</option></select></label><label>Duración base<input value="60 min · mixes.handlingTime" readOnly/></label><h3>Componentes configurables</h3><label className="zs-check-row"><input type="checkbox" checked={led} onChange={e=>setLed(e.target.checked)}/><span><b>Terapia LED · +20 min</b><small>Sin inventario</small></span></label><label className="zs-check-row"><input type="checkbox" defaultChecked/><span><b>Ampolleta vitamina C · +0 min</b><small>Requiere retención</small></span></label></section><section className="zs-card"><h3>Buffers</h3><div className="zs-buffer-row"><label>Antes<input type="number" value={before} onChange={e=>setBefore(Number(e.target.value))}/></label><label>Después<input type="number" value={after} onChange={e=>setAfter(Number(e.target.value))}/></label></div><div className="zs-total-time"><span>Duración ocupada</span><strong>{total} min</strong><small>60 base + {led?20:0} adicionales + {before} antes + {after} después</small></div><Evidence kind="pending">Product requiere duración canónica</Evidence></section></div></div>;
}

function Reminders({ second,setSecond,validated,setValidated,onHelp }: { second:boolean;setSecond:(v:boolean)=>void;validated:boolean;setValidated:(v:boolean)=>void;onHelp:(id:string)=>void }) {
  return <div className="zs-admin-content"><header className="zs-section-head"><div><Evidence kind="to-be"/><h2>Recordatorios de cita <Help id="reminder" onOpen={onHelp}/></h2><p>Canales esperados: correo y WhatsApp, sujetos a validación técnica.</p></div><button className="zs-primary" onClick={()=>setValidated(true)}>Validar configuración</button></header>{validated&&<div className="zs-warning-result"><b>Configuración completa</b><span>Correo disponible · WhatsApp pendiente de validación técnica en ambiente objetivo.</span></div>}<div className="zs-reminder-grid"><article><header><div><b>Primer recordatorio</b><span>Obligatorio</span></div><strong>24 horas antes</strong></header><Channel name="Correo cliente" checked/><Channel name="WhatsApp cliente" checked/><Channel name="Correo prestador" checked/><Channel name="WhatsApp prestador" checked={false}/></article><article><header><div><b>Segundo recordatorio</b><Toggle checked={second} onChange={setSecond} label={second?"Activo":"Inactivo"}/></div><select defaultValue="4"><option value="4">4 horas antes</option><option value="2">2 horas antes</option><option value="1">1 hora antes</option></select></header><Channel name="Correo cliente" checked={second}/><Channel name="WhatsApp cliente" checked={second}/><Channel name="Correo prestador" checked={false}/><Channel name="WhatsApp prestador" checked={false}/></article></div><div className="zs-inline-info"><Evidence kind="pending"/><p>Scheduling, plantillas, destinatarios, reintentos y entrega real deben validarse técnicamente.</p></div></div>;
}

function Channel({name,checked}:{name:string;checked:boolean}) { const [value,setValue]=useState(checked); return <Toggle checked={value} onChange={setValue} label={name}/>; }
